#!/bin/bash

# Get Path to script folder
DIR="$( cd "$( dirname "$0" )" && pwd )"
# Fix path in case of symlinks
DIR=$(cd "$DIR" && pwd -P)

# Check for .dotfiles file and add symlink
dotfiles="$HOME/.dotfiles"
if [ -L $dotfiles ]; then
	rm $dotfiles
fi
if [ -d $dotfiles ]; then
	echo "Found existing .dotfiles folder. Skipping directory."
else
	ln -s "$DIR" "$dotfiles"
fi

# Recursively map dotfiles to home directory
echo "Installing dotfiles"
while IFS= read -d $'\0' -r file ; do
	echo -n "Installing: $file - "
	b=$(basename $file)
	c="$HOME/$b"
	d="$file"
	if [ -L $c ]; then
		rm $c
	fi
	if [ -f $c ]; then
		echo "Skip."
	else
		ln -s "$d" "$c"
		echo "Success."
	fi
done < <(find "$DIR" -type f \( -iname ".*" ! -iname ".git" ! -iname ".gitmodules" ! -iname "*.swp" \) -print0)

# Load up new bash profile
echo "Loading Bash Profile"
source ~/.bash_profile

if [ ! -d "$HOME/.vim/bundle/vundle" ]; then
	git clone https://github.com/gmarik/vundle.git "$HOME/.vim/bundle/vundle"
	vim -u "$HOME/.vimrc.bundles" +BundleInstall! +BundleClean +qall
fi

# Update Local Vim Settings
echo "Updating local vim setings"
vim +BundleInstall! +BundleClean +qall
