#!/usr/bin/env bash

topics="bash
bin
git
newsbeuter
notmuch
R
slate
tmux
utils
vim
zsh"

for i in $topics
do
    echo "Stowing $i..."
    stow -t "$HOME" "$i"
done

# source ~/.bash_profile

# if [ ! -f "$HOME/.vim/autoload/plug.vim" ]; then
# 	curl -sfLo ~/.vim/autoload/plug.vim --create-dirs \
# 		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# fi
#
# if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
# 	git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm" --quiet
# 	if ! { [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; } then
# 		tmux source-file "$HOME/.tmux.conf"
# 	fi
# fi
