#!/usr/bin/env bash

stow -t "$HOME" bash
stow -t "$HOME" git
stow -t "$HOME" newsbeuter
stow -t "$HOME" notmuch
stow -t "$HOME" R
stow -t "$HOME" slate
stow -t "$HOME" tmux
stow -t "$HOME" utils
stow -t "$HOME" vim
stow -t "$HOME" zsh

mkdir -p "$HOME/bin"
stow -t "$HOME/bin/" bin

source "$HOME/.bash_profile"

if [ ! -f "$HOME/.vim/autoload/plug.vim" ]; then
	curl -sfLo ~/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
	git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm" --quiet
	if ! { [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; } then
		tmux source-file "$HOME/.tmux.conf"
	fi
fi
