#!/usr/bin/env bash
export DEBIAN_FRONTEND=noninteractive
apt-get update -y > /dev/null
sudo apt-get install -y python-software-properties software-properties-common
sudo add-apt-repository -y ppa:pi-rho/dev
sudo apt-get update -y > /dev/null
sudo apt-get install -y tmux=2.0-1~ppa1~t
apt-get -y install vim git-core silversearcher-ag

# Remove default dotfiles that may exist
if [ -f "/home/vagrant/.profile" ]; then 
	rm "/home/vagrant/.profile"
fi
if [ -f "/home/vagrant/.bashrc" ]; then 
	rm "/home/vagrant/.bashrc"
fi
if [ -f "/home/vagrant/.bash_profile" ]; then 
	rm "/home/vagrant/.bash_profile"
fi
if [ -f "/home/vagrant/.localrc" ]; then 
	rm "/home/vagrant/.localrc"
fi
if [ -f "/home/vagrant/.bash_logout" ]; then 
	rm "/home/vagrant/.bash_logout"
fi
if [ -f "/home/vagrant/.viminfo" ]; then 
	rm "/home/vagrant/.viminfo"
fi
su -c "git clone --depth 1 https://github.com/junegunn/fzf.git /home/vagrant/.fzf --quiet" vagrant
su -c "cd /home/vagrant/.fzf && ./install" vagrant
su -c "cd /home/vagrant/dotfiles && ./install" vagrant
