#!/usr/bin/env bash

# Return number of staged files in folder
gitstaged() {
  local s
  s=$(trimspace "$(git diff --cached --numstat 2> /dev/null | wc -l)" )
  if [ "0" == "${s}" ]; then
    s=""
  else
    s="${s} "
  fi
  echo "${s}"
}
