#!/usr/bin/env bash

vid2winppt () {
  if [ $# -eq 0 ]; then
    echo "Missing video to convert as argument."
  else
    if [ -f "$1" ] ; then
      echo "is the src greater than 720p? (Y/n)"
      read -r input
      if [[ "$input" == "Y" || "$input" == "y" || "$input" = "" ]]; then
        ffmpeg -i "$1" \
          -r 25 \
          -f mpeg \
          -vf "scale=-2:720:flags=lanczos" \
          -vcodec mpeg1video \
          -ar 48000 \
          -b:v 5000k \
          -b:a 128k \
          -acodec mp2 \
          -ar 44100 \
          -ac 1 \
          -y \
          "$(basename "${1%.*}")-720p".mpg
      else
        ffmpeg -i "$1" \
          -r 25 \
          -f mpeg \
          -vcodec mpeg1video \
          -ar 48000 \
          -b:v 5000k \
          -b:a 128k \
          -acodec mp2 \
          -ar 44100 \
          -ac 1 \
          -y \
          "$(basename "${1%.*}")".mpg
      fi
    else
      echo "Video file does not exist"
    fi
  fi
}
