#!/usr/bin/env bash

_contact() {
  local lis cur
  lis=$(find "${CONTACTS_DIR}" | sed -e 's/\..*$//')
  cur=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=( $(compgen -W "$lis" -- "$cur") )
}

contact() {
  : "${CONTACTS_DIR:?'CONTACTS_DIR ENV Var not set'}"
  if [ $# -eq 0 ]; then
    local file
    file=$(find "$CONTACTS_DIR" | grep "$*" | fzf --multi --select-1 --exit-0 --preview="cat ${CONTACTS_DIR}/{}" --preview-window=right:70%:wrap)
    [[ -n $file ]] && ${EDITOR:-vim} "${CONTACTS_DIR}/${file}"
  else
    case "$1" in
      "-d")
        rm "${CONTACTS_DIR}"/"$2"
        ;;
      *)
        $EDITOR "${CONTACTS_DIR}"/"$*"
        ;;
    esac
  fi
}
complete -F _contact contact
