#!/usr/bin/env bash

function convert_vid_for_web () {
  if [ $# -eq 0 ]; then
    echo "Missing video to convert as argument."
  else
    if [ -f "$1" ] ; then
      ffmpeg -i "$1" -b 1500k -vcodec libx264 -vpre slow -vpre baseline -g 30 "$(basename "${1%.*}")-web.mp4"
      ffmpeg -i "$1" -b 1500k -vcodec libvpx -acodec libvorbis -ab 160000 -f webm -g 30 "$(basename "${1%.*}")-web.webm"
      ffmpeg -i "$1" -b 1500k -vcodec libtheora -acodec libvorbis -ab 160000 -g 30 "$(basename "${1%.*}")-web.ogv"
    else
      echo "Video file does not exist"
    fi
  fi
}
