#!/usr/bin/env bash

# Return number of untracked files in folder
gituntracked() {
  local u
  u=$(trimspace "$(git ls-files --exclude-standard --others 2> /dev/null | wc -l)" )
  if [ "0" == "${u}" ]; then
    u=""
  else
    u="${u} "
  fi
  echo "${u}"
}
