#!/usr/bin/env bash

# Note taking function and command completion
_n() {
  local lis cur
  lis=$(ls -1 "${NOTE_DIR}" | sed -e 's/\..*$//')
  cur=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=( $(compgen -W "$lis" -- "$cur") )
}
n() {
  : "${NOTE_DIR:?'NOTE_DIR ENV Var not set'}"
  if [ $# -eq 0 ]; then
    local file
    file=$(ls -1 "${NOTE_DIR}" | \
      sed -e 's/\..*$//' | \
      fzf \
        --multi \
        --select-1 \
        --exit-0 \
        --preview="cat ${NOTE_DIR}/{}.md" \
        --preview-window=right:70%:wrap)
    [[ -n $file ]] && ${EDITOR:-vim} "${NOTE_DIR}/${file}.md"
  else
    case "$1" in
      "-d")
        rm "${NOTE_DIR}"/"$2".md
        ;;
      *)
        ${EDITOR:-vim} "${NOTE_DIR}"/"$*".md
        ;;
    esac
  fi
}
complete -F _n n
