#!/usr/bin/env bash
somalist() {
  tempfile="${HOME}/.somafm.tmp"
  if test "$(find "$tempfile" -mmin +$((60*24)))"; then
    rm "$tempfile"
  fi
  if [ -f "$tempfile" ]; then
    cat "$tempfile"
  else
    curl -s https://somafm.com/listen/ | awk -F '[<>]' '/MP3:/ { print $4 }' | awk -F '"' '{print $2}' | tr -d \\/ | tee "$tempfile"
  fi
}
soma() {
  mplayer -playlist http://somafm.com/"$1"
}
_soma() {
  if [ "${#COMP_WORDS[@]}" != "2" ]; then
    return
  fi
  COMPREPLY=($(compgen -W "$(somalist)" -- "${COMP_WORDS[1]}"))
}
complete -F _soma soma
