#!/usr/bin/env bash

function vid2ipad () {
  if [ $# -eq 0 ]; then
    echo "Missing video to convert as argument."
  else
    if [ -f "$1" ] ; then
      pname="$(basename "${1%.*}")-ipad"
      echo "is the src greater than 720p? (Y/n)"
      read -r input
      if [[ "$input" == "Y" || "$input" == "y" || "$input" = "" ]]; then
        ffmpeg -i "$1" \
          -vf "scale=-1:720:flags=lanczos" \
          -pix_fmt yuv420p -vcodec libx264 \
          -profile:v main \
          -level 3.1 \
          -preset medium \
          -crf 23 \
          -x264-params ref=4 \
          -acodec copy \
          -movflags +faststart \
          "$pname.mp4"
      else
        ffmpeg -i "$1" \
          -pix_fmt yuv420p \
          -vcodec libx264 \
          -profile:v main \
          -level 3.1 \
          -preset medium \
          -crf 23 \
          -x264-params ref=4 \
          -acodec copy \
          -movflags +faststart \
          "$pname.mp4"
      fi
    else
      echo "Video file does not exist"
    fi
  fi
}
